---
version: "3.7"

services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TAG: ${TAG}
    #restart: unless-stopped
    command: [ "-config", "/etc/xray/config.json" ]
    volumes:
      - ./config.json:/etc/xray/config.json:ro
    ports:
      - "443:443"
